# Generated by Django 5.2.6 on 2026-01-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_system', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile_pic/default.jpg', null=True, upload_to='profile_pic'),
        ),
    ]
